### ISSUE TITLE
RuntimeError while inferencing diffusion-based Text2World models (with multi-view data)

### ISSUE THREAD

**Issue by heesungsung** [nvidia-cosmos/cosmos-predict1#51]
Following the instruction from [here](https://github.com/nvidia-cosmos/cosmos-predict1/blob/main/examples/inference_diffusion_text2world_multiview.md),
I'm trying to inference with the model with the given example.

However, RuntimeError occurs :
```bash
(cosmos-predict1) hs@DESKTOP-OOKO9IP:~/cosmos-predict1$ CUDA_HOME=$CONDA_PREFIX PYTHONPATH=$(pwd) python (cosmos-predict1) hs@DESKTOP-OOKO9IP:~/cosmos-predict1$ CUDA_HOME=$CONDA_PREFIX PYTHONPATH=$(pwd) python cosmos_predict1/diffusion/inference/text2world_multiview.py     --checkpoint_dir checkpoints     --diffusion_transformer_dir Cosmos-Predict1-7B-Text2World-Sample-AV-Multiview     --prompt "${PROMPT}"     --prompt_left "${PROMPT_LEFT}"     --prompt_right "${PROMPT_RIGHT}"     --prompt_back "${PROMPT_BACK}"     --prompt_back_left "${PROMPT_BACK_LEFT}"     --prompt_back_right "${PROMPT_BACK_RIGHT}"     --offload_tokenizer     --offload_diffusion_transformer     --offload_text_encoder_model     --video_save_name diffusion-text2world-multiview-7b
[04-11 16:42:42|INFO|cosmos_predict1/utils/misc.py:127:set_random_seed] Using random seed 1.
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:17<00:00,  5.85s/it]
[04-11 16:43:14|INFO|cosmos_predict1/diffusion/inference/world_generation_pipeline.py:836:generate] Run with prompt: {'prompt': "The video is captured from a camera mounted on a car.
(skipped...)
 'prompt_back_right': 'The video is captured from a camera mounted on a car. The camera is facing the rear right side.'}
[04-11 16:50:34|INFO|cosmos_predict1/diffusion/inference/world_generation_pipeline.py:847:generate] Finish text embedding on prompt
[04-11 16:50:34|INFO|cosmos_predict1/diffusion/inference/world_generation_pipeline.py:850:generate] Run generation
[04-11 16:50:34|CRITICAL|cosmos_predict1/diffusion/networks/general_dit_multiview.py:178:build_pos_embed] Building positional embedding with rope3d class, impl <class 'cosmos_predict1.diffusion.module.position_embedding.MultiviewVideoRopePosition3DEmb'>

E! CuDNN (v90101 17) function cudnnBackendFinalize() called:
e!         Error: CUDNN_STATUS_EXECUTION_FAILED; Reason: rtc->loadModule()
e!         Error: CUDNN_STATUS_EXECUTION_FAILED; Reason: ptr.isSupported()
e!         Error: CUDNN_STATUS_EXECUTION_FAILED; Reason: engine_post_checks(*engine_iface, engine.getPerfKnobs(), req_size, engine.getTargetSMCount())
e!         Error: CUDNN_STATUS_EXECUTION_FAILED; Reason: finalize_internal()
e! Time: 2025-04-11T16:54:46.790965 (0d+0h+4m+12s since start)
e! Process=34053; Thread=34053; GPU=NULL; Handle=NULL; StreamId=NULL.

Traceback (most recent call last):
  File "/home/hs/cosmos-predict1/cosmos_predict1/diffusion/inference/text2world_multiview.py", line 228, in <module>
    demo(args)
  File "/home/hs/cosmos-predict1/cosmos_predict1/diffusion/inference/text2world_multiview.py", line 175, in demo
    generated_output = pipeline.generate(current_prompt)
  File "/home/hs/cosmos-predict1/cosmos_predict1/diffusion/inference/world_generation_pipeline.py", line 851, in generate
    videos = self._run_model_with_offload(
  File "/home/hs/cosmos-predict1/cosmos_predict1/diffusion/inference/world_generation_pipeline.py", line 288, in _run_model_with_offload
    sample = self._run_model(prompt_embedding, negative_prompt_embedding)
  File "/home/hs/cosmos-predict1/cosmos_predict1/diffusion/inference/world_generation_pipeline.py", line 806, in _run_model
    sample = generate_world_from_text(
  File "/home/hs/cosmos-predict1/cosmos_predict1/diffusion/inference/inference_utils.py", line 491, in generate_world_from_text
    sample = model.generate_samples_from_batch(
  File "/home/hs/cosmos-predict1/cosmos_predict1/diffusion/model/model_t2w_multiview.py", line 90, in generate_samples_from_batch
    net_output_cond = self.net(x=xt_scaled, timesteps=t, **condition.to_dict())
  File "/home/hs/anaconda3/envs/cosmos-predict1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/hs/anaconda3/envs/cosmos-predict1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/hs/cosmos-predict1/cosmos_predict1/diffusion/networks/general_dit.py", line 501, in forward
    x = block(
  File "/home/hs/anaconda3/envs/cosmos-predict1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/hs/anaconda3/envs/cosmos-predict1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/hs/cosmos-predict1/cosmos_predict1/diffusion/module/blocks.py", line 550, in forward
    x = block(
  File "/home/hs/anaconda3/envs/cosmos-predict1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/hs/anaconda3/envs/cosmos-predict1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/hs/cosmos-predict1/cosmos_predict1/diffusion/module/blocks.py", line 460, in forward
    x = x + gate_1_1_1_B_D * self.block(
  File "/home/hs/anaconda3/envs/cosmos-predict1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/hs/anaconda3/envs/cosmos-predict1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/hs/cosmos-predict1/cosmos_predict1/diffusion/module/blocks.py", line 327, in forward
    x_THW_B_D = self.attn(
  File "/home/hs/anaconda3/envs/cosmos-predict1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/hs/anaconda3/envs/cosmos-predict1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/hs/cosmos-predict1/cosmos_predict1/diffusion/module/attention.py", line 310, in forward
    return self.cal_attn(q, k, v, mask)
  File "/home/hs/cosmos-predict1/cosmos_predict1/diffusion/module/attention.py", line 285, in cal_attn
    out = self.attn_op(q, k, v, core_attention_bias_type="no_bias", core_attention_bias=None)  # [B, Mq, H, V]
  File "/home/hs/anaconda3/envs/cosmos-predict1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/hs/anaconda3/envs/cosmos-predict1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/hs/anaconda3/envs/cosmos-predict1/lib/python3.10/site-packages/transformer_engine/pytorch/attention.py", line 8175, in forward
    return self.fused_attention(
  File "/home/hs/anaconda3/envs/cosmos-predict1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1739, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/hs/anaconda3/envs/cosmos-predict1/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1750, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/hs/anaconda3/envs/cosmos-predict1/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 745, in _fn
    return fn(*args, **kwargs)
  File "/home/hs/anaconda3/envs/cosmos-predict1/lib/python3.10/site-packages/transformer_engine/pytorch/attention.py", line 7228, in forward
    output = FusedAttnFunc.apply(
  File "/home/hs/anaconda3/envs/cosmos-predict1/lib/python3.10/site-packages/torch/autograd/function.py", line 575, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
  File "/home/hs/anaconda3/envs/cosmos-predict1/lib/python3.10/site-packages/transformer_engine/pytorch/attention.py", line 6604, in forward
    out_ret, aux_ctx_tensors = fused_attn_fwd(
  File "/home/hs/anaconda3/envs/cosmos-predict1/lib/python3.10/site-packages/transformer_engine/pytorch/cpp_extensions/fused_attn.py", line 1082, in fused_attn_fwd
    output_tensors = tex.fused_attn_fwd(
RuntimeError: /TransformerEngine/transformer_engine/common/fused_attn/fused_attn_f16_arbitrary_seqlen.cu:300 in function operator(): cuDNN Error: [cudnn_frontend] Error: No execution plans support the graph.. For more information, enable cuDNN error logging by setting CUDNN_LOGERR_DBG=1 and CUDNN_LOGDEST_DBG=stderr in the environment.
```

It seems that the error is related to fused_attn_fwd function in transformer_engine library...
How can I fix it?

My cuDNN version is 9.1.1.

**Comment by sophiahhuang** [comment]
@heesungsung let me know if this solves the problem—I'll close the issue for now, but you're welcome to reopen it if anything comes up.

**Comment by heesungsung** [comment]
Yes, I'm using the version of 1.12.0.

Below are the parts of my pip lists:

```
torch                             2.6.0
torchaudio                        2.6.0
torchprofile                      0.0.4
torchvision                       0.21.0
...
transformer_engine                1.12.0
transformer_engine_cu12           1.12.0
transformer_engine_torch          1.12.0
transformers                      4.49.0
```

But I still have the same issue.

I also try with the new conda environment of cosmos-transfer1, and the same issue occurs:
```
RuntimeError: /TransformerEngine/transformer_engine/common/fused_attn/fused_attn_f16_arbitrary_seqlen.cu:300 in function operator(): cuDNN Error: [cudnn_frontend] Error: No execution plans support the graph.. For more information, enable cuDNN error logging by setting CUDNN_LOGERR_DBG=1 and CUDNN_LOGDEST_DBG=stderr in the environment.
E0501 20:55:34.559000 28658 site-packages/torch/distributed/elastic/multiprocessing/api.py:869] failed (exitcode: 1) local_rank: 0 (pid: 28683) of binary: /home/hs/anaconda3/envs/cosmos-transfer1/bin/python3.10
Traceback (most recent call last):
  File "/home/hs/anaconda3/envs/cosmos-transfer1/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/hs/anaconda3/envs/cosmos-transfer1/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 355, in wrapper
    return f(*args, **kwargs)
  File "/home/hs/anaconda3/envs/cosmos-transfer1/lib/python3.10/site-packages/torch/distributed/run.py", line 918, in main
    run(args)
  File "/home/hs/anaconda3/envs/cosmos-transfer1/lib/python3.10/site-packages/torch/distributed/run.py", line 909, in run
    elastic_launch(
  File "/home/hs/anaconda3/envs/cosmos-transfer1/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 138, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/hs/anaconda3/envs/cosmos-transfer1/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 269, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
cosmos_transfer1/diffusion/inference/transfer.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-05-01_20:55:34
  host      : DESKTOP-OOKO9IP.
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 28683)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

Can I reopen this issue? @sophiahhuang

**Comment by heesungsung** [comment]
I use WSL2 (Ubuntu 20.04) on Windows11.
I think this problem might be related with WSL...

Below are my hardware information:
- CPU Intel Core i9-12900K
- GPU NVIDIA GeForce RTX 4090
- CUDA 12.4 and cuDNN 9.1.1
- torch 2.6.0 + cu124

Let me know if you need more information.

**Comment by heesungsung** [comment]
> I use WSL2 (Ubuntu 22.04) on Windows11. I think this problem might be related with WSL...
> 
> Below are my hardware information:
> 
> * CPU Intel Core i9-12900K
> * GPU NVIDIA GeForce RTX 4090
> * CUDA 12.4 and cuDNN 9.1.1
> * torch 2.6.0 + cu124
> 
> Let me know if you need more information.

Additionally, I met two more errors before this problem (and I solved it).

**1. ImportError: libcudnn.so.9: cannot open shared object file: No such file or directory**
```
(cosmos-predict1) hs@DESKTOP-OOKO9IP:/usr/local$ python
Python 3.10.16 | packaged by conda-forge | (main, Apr  8 2025, 20:53:32) [GCC 13.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hs/anaconda3/envs/cosmos-predict1/lib/python3.10/site-packages/torch/__init__.py", line 405, in <module>
    from torch._C import *  # noqa: F403
ImportError: libcudnn.so.9: cannot open shared object file: No such file or directory
```
I solved it by fixing the version of cuDNN to 9.1.1.

**2. ImportError: libnccl.so.2: cannot open shared object file: No such file or directory**
```
(cosmos-predict1) hs@DESKTOP-OOKO9IP:/usr/local$ pip install transformer-engine[pytorch]==1.12.0
Collecting transformer-engine==1.12.0 (from transformer-engine[pytorch]==1.12.0)

...(skipped)

Building wheels for collected packages: transformer-engine-torch
  Building wheel for transformer-engine-torch (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [327 lines of output]
      /home/hs/anaconda3/envs/cosmos-predict1/lib/python3.10/site-packages/setuptools/_distutils/dist.py:289: UserWarning: Unknown distribution option: 'tests_require'
        warnings.warn(msg)
      running bdist_wheel
      running build
      running build_ext
      /home/hs/anaconda3/envs/cosmos-predict1/lib/python3.10/site-packages/torch/utils/cpp_extension.py:458: UserWarning: There are no /home/hs/anaconda3/envs/cosmos-predict1/bin/x86_64-conda-linux-gnu-c++ version bounds defined for CUDA version 12.4
        warnings.warn(f'There are no {compiler_name} version bounds defined for CUDA version {cuda_str_version}')
      building 'transformer_engine_torch' extension
      creating /tmp/pip-install-lum_z6fo/transformer-engine-torch_2e74730e5b2a4005bde9571418b6d573/build/temp.linux-x86_64-cpython-310/csrc
      creating /tmp/pip-install-lum_z6fo/transformer-engine-torch_2e74730e5b2a4005bde9571418b6d573/build/temp.linux-x86_64-cpython-310/csrc/extensions
      creating /tmp/pip-install-lum_z6fo/transformer-engine-torch_2e74730e5b2a4005bde9571418b6d573/build/temp.linux-x86_64-cpython-310/csrc/extensions/multi_tensor
      creating /tmp/pip-install-lum_z6fo/transformer-engine-torch_2e74730e5b2a4005bde9571418b6d573/build/temp.linux-x86_64-cpython-310/csrc/userbuffers
      Emitting ninja build file /tmp/pip-install-lum_z6fo/transformer-engine-torch_2e74730e5b2a4005bde9571418b6d573/build/temp.linux-x86_64-cpython-310/build.ninja...
      Compiling objects...
      Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
 
...(skipped)

        File "/home/hs/anaconda3/envs/cosmos-predict1/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 1869, in _write_ninja_file_and_compile_objects
          _run_ninja_build(
        File "/home/hs/anaconda3/envs/cosmos-predict1/lib/python3.10/site-packages/torch/utils/cpp_extension.py", line 2225, in _run_ninja_build
          raise RuntimeError(message) from e
      RuntimeError: Error compiling objects for extension
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for transformer-engine-torch
  Running setup.py clean for transformer-engine-torch
Failed to build transformer-engine-torch
ERROR: Failed to build installable wheels for some pyproject.toml based projects (transformer-engine-torch)
```
I solved it by installing Nvidia NCCL.

**Comment by arieling** [comment]
@heesungsung Thank you for the update!!! and great seems you have figured it out. 
Close the the issue for now please re-open if you have further questions.
